# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_customuser_meta_mask_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='meta_mask_address',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='meta mask address'),
        ),
    ]
