# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-28 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20230428_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='meta_mask_address',
            new_name='wallet_address',
        ),
    ]
