# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20230428_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='meta_mask_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='k',
            field=models.CharField(default='', max_length=254, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
