# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20230428_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adf',
            field=models.CharField(blank=True, max_length=30, verbose_name='as'),
        ),
    ]
