# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20230428_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_made',
            field=models.BooleanField(default=False, verbose_name='payment made or not'),
        ),
    ]
