# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_customuser_encrypted_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_private_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pri_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
