# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20230430_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pri_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='private key'),
        ),
    ]
