# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-30 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_customuser_pri_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(blank=True, help_text='Required. to make payments, enter a private key', max_length=42, verbose_name='Pri key'),
        ),
    ]
