# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-04-30 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20230430_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bearable',
            field=models.DecimalField(decimal_places=15, max_digits=40, verbose_name='bearable cost'),
        ),
    ]
