# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2023-05-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_request_tx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bearable',
            field=models.DecimalField(decimal_places=5, max_digits=40, verbose_name='bearable cost'),
        ),
    ]
