# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2023-05-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20230502_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bearable',
            field=models.DecimalField(decimal_places=2, max_digits=40, verbose_name='bearable cost'),
        ),
    ]
